// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0HQFAvqCW2QYzihn1ZM9xcvo_HgzUpqM',
    appId: '1:794124181844:web:97478f56c8981a3f8a68c1',
    messagingSenderId: '794124181844',
    projectId: 'answerfive-15710',
    authDomain: 'answerfive-15710.firebaseapp.com',
    storageBucket: 'answerfive-15710.appspot.com',
    measurementId: 'G-69TX6ZX7ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Nl5YSZ41ggeqt-MiSxINX68kvcFFSZw',
    appId: '1:794124181844:android:ca84efc06d8350d58a68c1',
    messagingSenderId: '794124181844',
    projectId: 'answerfive-15710',
    storageBucket: 'answerfive-15710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJy3lYVZKs7ZWqC1mh1GB6vkU5X7FJbHg',
    appId: '1:794124181844:ios:9a4015744d8458cf8a68c1',
    messagingSenderId: '794124181844',
    projectId: 'answerfive-15710',
    storageBucket: 'answerfive-15710.appspot.com',
    iosClientId: '794124181844-m5dph3m9q4fb8t0ikfc2tqpr438115n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.answerFive',
  );
}
